In [1]:
# =======================================================
# Imports
# =======================================================

import pandas as pd
import numpy as np
import streamlit as st
import altair as alt

import pandas as pd
import numpy as np
import streamlit as st
import altair as alt
import numpy as np
import json  
import random

import altair as alt
alt.data_transformers.enable("vegafusion")

from painel_strava_agrupamentos import *

In [6]:
# =======================================================
# Datasets
# =======================================================
df_atividades_todos = pd.read_csv('datasets/predados/atividades_fisicas_todos.csv', sep=',', encoding="ISO-8859-1")
df_atividades_completo_2020 = pd.read_csv('datasets/predados/atividades_fisicas_2020.csv', sep=',', encoding="ISO-8859-1")
df_atividades_completo_2021 = pd.read_csv('datasets/predados/atividades_fisicas_2021.csv', sep=',', encoding="ISO-8859-1")
df_atividades_completo_2022 = pd.read_csv('datasets/predados/atividades_fisicas_2022.csv', sep=',', encoding="ISO-8859-1")
df_atividades_completo_2023 = pd.read_csv('datasets/predados/atividades_fisicas_2023.csv', sep=',', encoding="ISO-8859-1")
df_atividades_completo_2024 = pd.read_csv('datasets/predados/atividades_fisicas_2024.csv', sep=',', encoding="ISO-8859-1")
df_atividades_completo_2025 = pd.read_csv('datasets/predados/atividades_fisicas_2025.csv', sep=',', encoding="ISO-8859-1")

df_atividades_simplificado_todos = pd.read_csv('datasets/predados/atividades_fisicas_simplificado_todos.csv', sep=',', encoding="ISO-8859-1")
df_atividades_simplificado_2020 = pd.read_csv('datasets/predados/atividades_fisicas_simplificado_2020.csv', sep=',', encoding="ISO-8859-1")
df_atividades_simplificado_2021 = pd.read_csv('datasets/predados/atividades_fisicas_simplificado_2021.csv', sep=',', encoding="ISO-8859-1")
df_atividades_simplificado_2022 = pd.read_csv('datasets/predados/atividades_fisicas_simplificado_2022.csv', sep=',', encoding="ISO-8859-1")
df_atividades_simplificado_2023 = pd.read_csv('datasets/predados/atividades_fisicas_simplificado_2023.csv', sep=',', encoding="ISO-8859-1")
df_atividades_simplificado_2024 = pd.read_csv('datasets/predados/atividades_fisicas_simplificado_2024.csv', sep=',', encoding="UTF-8")
df_atividades_simplificado_2025 = pd.read_csv('datasets/predados/atividades_fisicas_simplificado_2025.csv', sep=',', encoding="ISO-8859-1")

In [10]:
df_teste = pd.read_csv('datasets/predados/atividades_fisicas_simplificado_2024.csv', sep=',', encoding="ISO-8859-1")
df_teste

,Unnamed: 0.1,Unnamed: 0,Activity ID,Activity Date,Activity Name,Activity Type,Activity Description,Elapsed Time,Distance,Max Heart Rate,Filename,Max Speed,Average Speed,Calories,data_ano,data_mes,dia_semana,tempo_min
0,0,925,10498660575,"Jan 3, 2024, 9:15:34 PM",Caminhada com Bernardo na UFPE,Walk,NaN,5420,6.67,143.0,activities/11234256016.tcx.gz,5.717453,1.231683,490.0,2024,1,Quarta,90.333333
1,1,926,10498660618,"Jan 3, 2024, 10:13:33 PM",Corrida na UFPE,Run,NaN,1554,4.07,184.0,activities/11234256144.tcx.gz,17.325399,2.768029,328.0,2024,1,Quarta,25.900000
2,2,927,10498660632,"Jan 4, 2024, 10:53:57 PM",Treino academia P1,Weight Training,NaN,1107,0.00,110.0,activities/11234256231.tcx.gz,0.000000,0.000000,98.0,2024,1,Quinta,18.450000
3,3,928,10498660755,"Jan 4, 2024, 11:12:46 PM",Treino academia P2,Weight Training,NaN,2870,0.00,131.0,activities/11234256310.tcx.gz,0.000000,0.000000,316.0,2024,1,Quinta,47.833333
4,4,929,10528147729,"Jan 9, 2024, 10:27:09 PM",Afternoon Workout,Workout,NaN,4048,0.00,127.0,activities/11265235805.tcx.gz,0.000000,0.000000,407.0,2024,1,Terca,67.466667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,281,1206,13131520690,"Dec 16, 2024, 8:59:28 PM",Lunch Workout,Workout,NaN,3173,0.00,126.0,activities/14003560755.tcx.gz,0.000000,0.000000,310.0,2024,12,Segunda,52.883333
282,282,1207,13145763309,"Dec 18, 2024, 10:13:22 PM",Afternoon Workout,Workout,NaN,4170,0.00,150.0,activities/14018777980.tcx.gz,0.000000,0.000000,433.0,2024,12,Quarta,69.500000
283,283,1208,13158292102,"Dec 20, 2024, 10:07:25 PM",Afternoon Workout,Workout,NaN,4198,0.00,130.0,activities/14032271135.tcx.gz,0.000000,0.000000,435.0,2024,12,Sexta,69.966667
284,284,1209,13165045768,"Dec 21, 2024, 10:35:43 PM",Evening Walk,Walk,NaN,739,1.01,138.0,activities/14039540272.tcx.gz,2.370359,1.401384,100.0,2024,12,Sabado,12.316667
285,285,1210,13165045812,"Dec 21, 2024, 10:48:10 PM",Evening Run,Run,NaN,2724,6.02,178.0,activities/14039540304.tcx.gz,3.995853,2.311569,472.0,2024,12,Sabado,45.400000

In [ ]:

colunas_desejadas = ['data_ano', 'data_mes', 'dia_semana', 'Activity Name',	'Activity Type', 'Elapsed Time',	'Distance', 'Calories', 'tempo_min']

novo_df = df_teste[colunas_desejadas]
novo_df

,data_ano,data_mes,dia_semana,Activity Name,Activity Type,Elapsed Time,Distance,Calories,tempo_min
0,2024,1,Quarta,Caminhada com Bernardo na UFPE,Walk,5420,6.67,490.0,90.333333
1,2024,1,Quarta,Corrida na UFPE,Run,1554,4.07,328.0,25.900000
2,2024,1,Quinta,Treino academia P1,Weight Training,1107,0.00,98.0,18.450000
3,2024,1,Quinta,Treino academia P2,Weight Training,2870,0.00,316.0,47.833333
4,2024,1,Terca,Afternoon Workout,Workout,4048,0.00,407.0,67.466667
...,...,...,...,...,...,...,...,...,...
281,2024,12,Segunda,Lunch Workout,Workout,3173,0.00,310.0,52.883333
282,2024,12,Quarta,Afternoon Workout,Workout,4170,0.00,433.0,69.500000
283,2024,12,Sexta,Afternoon Workout,Workout,4198,0.00,435.0,69.966667
284,2024,12,Sabado,Evening Walk,Walk,739,1.01,100.0,12.316667
285,2024,12,Sabado,Evening Run,Run,2724,6.02,472.0,45.400000

In [14]:
def atividades_ano_mes(df_teste, ano, mes):
    colunas_desejadas = ['data_ano', 'data_mes', 'dia_semana', 'Activity Name',	'Activity Type', 'Elapsed Time',	'Distance', 'Calories', 'tempo_min']

    novo_df = df_teste[colunas_desejadas]
    novo_df = novo_df[(novo_df['data_ano'] == ano) & (novo_df['data_mes'] == mes)]
    
    return novo_df

In [15]:
df_2024_01 = atividades_ano_mes(df_teste, 2024, 1)
df_2024_01

,data_ano,data_mes,dia_semana,Activity Name,Activity Type,Elapsed Time,Distance,Calories,tempo_min
0,2024,1,Quarta,Caminhada com Bernardo na UFPE,Walk,5420,6.67,490.0,90.333333
1,2024,1,Quarta,Corrida na UFPE,Run,1554,4.07,328.0,25.900000
2,2024,1,Quinta,Treino academia P1,Weight Training,1107,0.00,98.0,18.450000
3,2024,1,Quinta,Treino academia P2,Weight Training,2870,0.00,316.0,47.833333
4,2024,1,Terca,Afternoon Workout,Workout,4048,0.00,407.0,67.466667
5,2024,1,Sexta,Evening Walk,Walk,2642,3.79,372.0,44.033333
6,2024,1,Quarta,Evening Walk,Walk,1257,2.01,164.0,20.950000
7,2024,1,Quarta,Evening Run,Run,1781,4.01,394.0,29.683333
8,2024,1,Quarta,Evening Walk,Walk,938,1.27,189.0,15.633333
9,2024,1,Quinta,Afternoon Workout,Workout,3504,0.00,362.0,58.400000
10,2024,1,Terca,Afternoon Workout,Workout,2761,0.00,270.0,46.016667
11,2024,1,Quarta,Night Workout,Workout,765,1.68,237.0,12.750000
12,2024,1,Quarta,Afternoon Run,Run,1438,1.64,235.0,23.966667
13,2024,1,Quinta,Evening Run,Run,872,2.04,180.0,14.533333
14,2024,1,Quinta,Caminhada de Aquecimento,Walk,1799,2.00,197.0,29.983333
15,2024,1,Quinta,Caminhada de relaxamento,Walk,1353,2.04,184.0,22.550000
16,2024,1,Sabado,Caminhada de Aquecimento,Walk,1119,1.03,82.0,18.650000
17,2024,1,Sabado,Corrida na UFPE,Run,1922,5.01,341.0,32.033333
18,2024,1,Segunda,Treino academia,Weight Training,3427,0.00,336.0,57.116667
19,2024,1,Terca,Treino academia,Weight Training,3429,0.00,376.0,57.150000
20,2024,1,Quinta,Caminhada de Aquecimento,Walk,980,1.51,134.0,16.333333
21,2024,1,Quinta,Corrida rÃÂÃÂ¡pida na UFPE,Run,2047,4.39,406.0,34.116667
22,2024,1,Sabado,Caminhada na UFPE,Walk,2114,2.00,176.0,35.233333
23,2024,1,Segunda,Treino academia,Weight Training,376,0.01,392.0,6.266667
24,2024,1,Quarta,Treino academia,Weight Training,3698,0.00,381.0,61.633333
25,2024,1,Terca,Treino academia,Weight Training,4922,0.00,453.0,82.033333